### PR TITLE
Workaround buffer size mismatch

### PR DESCRIPTION
**Pull request by hujiajie**

### CODE REVIEW

**Comment by gyagp** [comment]
Please don't use magic number everywhere.

**Comment by hujiajie** [comment]
Magic numbers are already used everywhere:

https://github.com/webatintel/aquarium/blob/5cd099d4f02cb53477c6c5f3d8e1a7ae71d9240b/src/aquarium-optimized/dawn/GenericModelDawn.h#L56
https://github.com/webatintel/aquarium/blob/5cd099d4f02cb53477c6c5f3d8e1a7ae71d9240b/src/aquarium-optimized/dawn/OutsideModelDawn.cpp#L108
https://github.com/webatintel/aquarium/blob/5cd099d4f02cb53477c6c5f3d8e1a7ae71d9240b/src/aquarium-optimized/dawn/SeaweedModelDawn.cpp#L99

We need a separate patch to fix all in one time, either before or after this one. WDYT?

**Comment by gyagp** [comment]
Then LGTM. 
Please do the changes ASAP after this patch. Magic numbers really make it hard to maintain the code.

**Comment by hujiajie** [comment]
I'm afraid the magic number clean-up will be scheduled much later because of the totally broken instanced rendering path.

**Pull request merged**
